workspace = { members = ["enc_macros"] }
[package]
name = "embed_str_ex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
enc_macros = { path = "./enc_macros" }

[profile.release]
strip=true
